services:
  php:
    image: creativewind-php:8.4
    container_name: creativewind-php
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html/
    ports:
      - "9000:80"
    networks:
      - creativewind_network
    depends_on:
      - db

  db:
    image: creativewind-mysql:9.5
    container_name: creativewind-db
    restart: no
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
    ports:
      - "3306:3306"
    volumes:
      - db-data-creativewind:/var/lib/mysql
    networks:
      - creativewind_network

  phpmyadmin:
    platform: linux/arm64/v8
    image: phpmyadmin:5.2.3
    container_name: creativewind-pma
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: noPassword
      PMA_ARBITRARY: 1
    networks:
      - creativewind_network

  mailpit:
    image: axllent/mailpit
    container_name: creativewind-mailpit
    restart: unless-stopped
    volumes:
        - ./data:/data
    ports:
        - "1025:1025"   # SMTP port
        - "8025:8025"   # Web UI port
    environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - creativewind_network


volumes:
  db-data-creativewind:

networks:
  creativewind_network:
